package rs.teslaris.project.model.funding;

public enum FundingCallContributionType {
    ORGANIZER,
    COORDINATOR,
    ASSESSMENT_BOARD_PRESIDENT,
    ASSESSMENT_BOARD_VICEPRESIDENT,
    ASSESSMENT_BOARD_MEMBER,
    ASSESSMENT_EVALUATOR,
    ASSESSMENT_SPECIALIST,
    ASSESSMENT_OTHER,
    APPLICANT,
    OTHER_CONTRIBUTORS
}
