package rs.teslaris.core.model.commontypes;

public enum ApplicableEntityType {
    MONOGRAPH,
    EVENT,
    DOCUMENT,
    PERSON,
    ORGANISATION_UNIT,
    PUBLICATION_SERIES,
    ALL,
    MONOGRAPH_PUBLICATION,
    JOURNAL_PUBLICATION,
    PROCEEDINGS_PUBLICATION,
    PATENT,
    MATERIAL_PRODUCT,
    GENETIC_MATERIAL,
    DATASET,
    THESIS,
    PRIZE,
    CONFERENCE,
    EXHIBITION,
    COURSE,
    OTHER_EVENT,
    JOURNAL,
    BOOK_SERIES,
    PROCEEDINGS,
    INTANGIBLE_PRODUCT,
    PERFORMANCE_RELATED_OUTPUT
}
