package rs.teslaris.core.model.commontypes;

public enum ExportableEndpointType {
    PERSON_SEARCH,
    DOCUMENT_SEARCH,
    ORGANISATION_UNIT_SEARCH,
    PERSON_OUTPUTS,
    ORGANISATION_UNIT_OUTPUTS,
    ORGANISATION_UNIT_EMPLOYEES,
    THESIS_SIMPLE_SEARCH,
    THESIS_ADVANCED_SEARCH,
    DOCUMENT_ADVANCED_SEARCH,
    AUTHOR_REPRINT_DOCUMENTS_SEARCH,
    PERSON_SEARCH_ADVANCED,
    ORGANISATION_UNIT_SEARCH_ADVANCED
}
