package rs.teslaris.core.model.commontypes;

public enum NotificationType {
    NEW_PAPER_HARVESTED,
    ADDED_TO_PUBLICATION,
    NEW_OTHER_NAME_DETECTED,
    NEW_IMPORTS_HARVESTED,
    DEDUPLICATION_SCAN_FINISHED,
    FOUND_POTENTIAL_CLAIMS,
    SCHEDULED_TASK_COMPLETED,
    NEW_EVENTS_TO_CLASSIFY,
    NEW_PUBLICATIONS_TO_ASSESS,
    PROMOTION_NOTIFICATION,
    NEW_ENTITY_CREATION,
    NEW_DOCUMENTS_FOR_VALIDATION,
    NEW_AUTHOR_UNBINDING,
    ALL_AUTHORS_UNBINDED
}
