package rs.teslaris.core.model.commontypes;

public enum ScheduledTaskType {
    JOURNAL_CLASSIFICATION,
    JOURNAL_CLASSIFICATION_LOADING,
    REINDEXING,
    DOCUMENT_BACKUP,
    THESIS_LIBRARY_BACKUP,
    REGISTRY_BOOK_REPORT_GENERATION,
    IF5_JCI_RANK_COMPUTATION,
    INDICATOR_LOADING,
    PUBLICATION_CLASSIFICATION,
    REPORT_GENERATION,
    PUBLICATION_HARVEST,
    AUTHOR_CENTRIC_PUBLICATION_HARVEST,
    OAI_PMH_HARVEST,
    UNMANAGED_DOCUMENTS_DELETION,
    PUBLIC_REVIEW_END_DATE_CHECK,
    SKG_IF_HARVEST,
    MAINTENANCE
}
