package rs.teslaris.core.model.commontypes;

public enum ScheduledTaskType {
    JOURNAL_CLASSIFICATION,
    JOURNAL_CLASSIFICATION_LOADING,
    REINDEXING,
    DOCUMENT_BACKUP,
    THESIS_LIBRARY_BACKUP,
    REGISTRY_BOOK_REPORT_GENERATION,
    IF5_RANK_COMPUTATION,
    INDICATOR_LOADING,
    PUBLICATION_CLASSIFICATION,
    REPORT_GENERATION,
    PUBLICATION_HARVEST,
    AUTHOR_CENTRIC_PUBLICATION_HARVEST
}
