package rs.teslaris.core.util.notificationhandling;

public enum NotificationAction {
    APPROVE,
    REMOVE_FROM_PUBLICATION,
    PERFORM_DEDUPLICATION,
    BROWSE_CLAIMABLE_DOCUMENTS,
    PERFORM_EVENT_CLASSIFICATION,
    PERFORM_DOCUMENT_ASSESSMENT,
    GO_TO_PROMOTIONS_PAGE,
    GO_TO_HARVESTER_PAGE,
    NAVIGATE_TO_URL,
    GO_TO_VALIDATION_PAGE,
    GO_TO_UNBINDED_PUBLICATIONS_PAGE,
    REMOVE_EMPLOYEES_FROM_PUBLICATION
}
