package rs.teslaris.core.indexmodel;

public enum DocumentPublicationType {
    JOURNAL_PUBLICATION,
    PROCEEDINGS,
    PROCEEDINGS_PUBLICATION,
    MONOGRAPH,
    INTELLECTUAL_PROPERTY,
    INTANGIBLE_PRODUCT,
    MONOGRAPH_PUBLICATION,
    THESIS,
    MATERIAL_PRODUCT,
    GENETIC_MATERIAL,
    PERFORMANCE_RELATED_OUTPUT
}
