package rs.teslaris.core.indexmodel;

public enum DocumentPublicationType {
    JOURNAL_PUBLICATION,
    PROCEEDINGS,
    PROCEEDINGS_PUBLICATION,
    MONOGRAPH,
    PATENT,
    INTANGIBLE_PRODUCT,
    DATASET,
    MONOGRAPH_PUBLICATION,
    THESIS,
    MATERIAL_PRODUCT,
    GENETIC_MATERIAL
}
