package rs.teslaris.core.indexmodel;

public enum EntityType {
    BOOK_SERIES,
    PUBLICATION,
    EVENT,
    JOURNAL,
    ORGANISATION_UNIT,
    PERSON,
    PUBLISHER,
    USER_ACCOUNT,
    MONOGRAPH,
    PROCEEDINGS,
    DOCUMENT_FILE,
    PRIZE,
    CONFERENCE,
    EXHIBITION,
    ASSESSMENT_POINTS,
    FUNDING_PROGRAM,
    FUNDING_CALL,
    PROJECT,
    COURSE,
    OTHER_EVENT
}
