package rs.teslaris.project.model.project;

public enum PersonProjectInvestigationRole {
    RESEARCHER,
    PHD_STUDENT_FELLOW,
    TECHNICAL_DEVELOPMENT,
    MASTER_STUDENT_FELLOW,
    SUPERVISOR,
    POSTDOC,
    POSTDOC_FELLOW,
    RESEARCH_FELLOW,
    INTEGRATION_INTO_RESEARCH_GRANT_FELLOW,
    SCIENTIFIC_INITIATION_FELLOW,
    RESEARCH_TECHNICIAN_FELLOW,
    INVITED_SCIENTIST_FELLOW,
    SCIENCE_AND_TECHNOLOGY_MANAGEMENT_FELLOW,
    SCIENTIFIC_EXPEDITION,
    OTHER
}
