package rs.teslaris.core.model.document;

public enum ResourceType {
    PREPRINT,
    OFFICIAL_PUBLICATION,
    SUPPLEMENT,
    PROOF,
    IMAGE,
    STATEMENT,
    ADVISOR_CONFLICT_OF_INTEREST,
    CONTRACT,
    REPORTING_TEMPLATE,
    PROGRAM_DESCRIPTION,
    CALL_TEXT,
    APPLICATION_TEMPLATE,
    OTHER
}
