@startuml journalPublication

    !includesub model.puml!Multilingual_Content
    !includesub model.puml!Organisation_Unit
    !includesub model.puml!Document
    !includesub model.puml!Journal_Publication
    !includesub model.puml!Person_Contribution
    !includesub model.puml!Person_Document_Contribution
    !includesub model.puml!Person
    !includesub model.puml!Event

@enduml