package rs.teslaris.assessment.model;

public enum ReportType {
    TABLE_63,
    TABLE_67,
    TABLE_67_POSITIONS,
    TABLE_64,
    TABLE_TOP_LEVEL_INSTITUTION,
    TABLE_TOP_LEVEL_INSTITUTION_SUMMARY,
    TABLE_TOP_LEVEL_INSTITUTION_COLORED,
}
